name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Create package.json
        run: |
          cat > package.json << 'EOL'
          {
            "name": "expenses-pwa",
            "private": true,
            "version": "0.0.0",
            "type": "module",
            "scripts": {
              "dev": "vite",
              "build": "vite build",
              "lint": "eslint .",
              "preview": "vite preview"
            },
            "dependencies": {
              "@radix-ui/react-dialog": "^1.1.6",
              "@radix-ui/react-dropdown-menu": "^2.0.6",
              "@radix-ui/react-popover": "^1.1.6",
              "@radix-ui/react-slot": "^1.0.2",
              "@radix-ui/react-toast": "^1.2.6",
              "@supabase/supabase-js": "^2.49.1",
              "class-variance-authority": "^0.7.0",
              "clsx": "^2.1.0",
              "date-fns": "^3.6.0",
              "date-fns-tz": "^3.2.0",
              "lucide-react": "^0.344.0",
              "react": "^18.3.1",
              "react-day-picker": "^8.10.0",
              "react-dom": "^18.3.1",
              "tailwind-merge": "^2.2.1"
            },
            "devDependencies": {
              "@eslint/js": "^9.9.1",
              "@types/react": "^18.3.5",
              "@types/react-dom": "^18.3.0",
              "@vitejs/plugin-react": "^4.3.1",
              "autoprefixer": "^10.4.18",
              "babel-plugin-transform-remove-console": "^6.9.4",
              "eslint": "^9.9.1",
              "eslint-plugin-react-hooks": "^5.1.0-rc.0",
              "eslint-plugin-react-refresh": "^0.4.11",
              "globals": "^15.9.0",
              "postcss": "^8.4.35",
              "rimraf": "^5.0.10",
              "rollup-plugin-visualizer": "^5.14.0",
              "tailwindcss": "^3.4.1",
              "typescript": "^5.5.3",
              "typescript-eslint": "^8.3.0",
              "vite": "^5.4.2",
              "vite-plugin-pwa": "^0.19.2"
            }
          }
          EOL
          
      - name: Create vite.config.js
        run: |
          cat > vite.config.js << 'EOL'
          import { defineConfig } from 'vite';
          import react from '@vitejs/plugin-react';
          import { VitePWA } from 'vite-plugin-pwa';
          import path from 'path';
          
          const supabaseUrl = 'https://mnucrulwdurskwofsgwp.supabase.co';
          const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1udWNydWx3ZHVyc2t3b2ZzZ3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNzg3ODksImV4cCI6MjA1Njc1NDc4OX0.39iA0f1vEH2K8ygEobuv6O_FR88Fm8H2UXHzPkAZmm60';
          
          export default defineConfig(({ mode }) => {
            const isProduction = mode === 'production' || mode === 'analyze';
            const base = isProduction ? '/CeA-APP/' : '/';
          
            const plugins = [
              react({
                babel: {
                  plugins: isProduction ? ['transform-remove-console'] : []
                }
              }),
              VitePWA({
                registerType: 'autoUpdate',
                includeAssets: ['favicon.ico', 'apple-touch-icon.png', 'mask-icon.svg'],
                manifest: {
                  name: 'EXPENSES',
                  short_name: 'EXPENSES',
                  theme_color: '#073763',
                  icons: [
                    {
                      src: '/icon-192.png',
                      sizes: '192x192',
                      type: 'image/png'
                    },
                    {
                      src: '/icon-512.png',
                      sizes: '512x512',
                      type: 'image/png'
                    }
                  ]
                },
                workbox: {
                  globPatterns: ['**/*.{js,css,html,ico,png,svg,jpg,jpeg,gif,webp}'],
                  runtimeCaching: [
                    {
                      urlPattern: /^https:\/\/mnucrulwdurskwofsgwp\.supabase\.co\/.*/i,
                      handler: 'NetworkFirst',
                      options: {
                        cacheName: 'supabase-api-cache',
                        expiration: {
                          maxEntries: 100,
                          maxAgeSeconds: 60 * 60 * 24
                        }
                      }
                    }
                  ]
                }
              })
            ];
          
            return {
              base,
              plugins,
              resolve: {
                alias: {
                  '@': path.resolve(__dirname, './src')
                }
              },
              build: {
                outDir: 'dist',
                emptyOutDir: true,
                sourcemap: false
              },
              define: {
                'import.meta.env.VITE_SUPABASE_URL': JSON.stringify(supabaseUrl),
                'import.meta.env.VITE_SUPABASE_ANON_KEY': JSON.stringify(supabaseAnonKey),
                'process.env.NODE_ENV': JSON.stringify(isProduction ? 'production' : 'development')
              }
            };
          });
          EOL
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true 