// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvxgalscxlgjcbgqkukm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2eGdhbHNjeGxnamNiZ3FrdWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzUxNjEsImV4cCI6MjA2NDU1MTE2MX0.AwZxVUE5HQJOHSox_6r5xkDhvNIm9QUHlFokAF2JpK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);