[build]
  base = "project"
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Force cache invalidation with this value
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Configurações para o Supabase
[template.environment]
  VITE_SUPABASE_URL = "URL do seu projeto Supabase"
  VITE_SUPABASE_ANON_KEY = "Chave anônima do seu projeto Supabase"
  
# Force new deploy - clear cache - timestamp: 2025-03-15T11:30:00Z 